### PR TITLE
lab2

### PR DESCRIPTION
**Pull request by artyom-mankevich**

### CODE REVIEW

**Comment by katetushkan** [comment]
Why did u close this pr?

**Comment by artyom-mankevich** [comment]
IDK, thought you missed it and wanted to show it in person, will reopen in a sec

**Comment by katetushkan** [comment]
> IDK, thought you missed it and wanted to show it in person, will reopen in a sec

no, I'll check here, everything looks good, but pls add html tags on top of ur mockup, or add it to the  group's name in Figma, so I could see how u divided ur app.

**Comment by artyom-mankevich** [comment]
@katetushkan I added html tags to the groups names in figma

**Comment by katetushkan** [comment]
> @katetushkan I added html tags to the groups names in figma
Good, I give u 10.

**Review by katetushkan — APPROVED** [review]
Good, I give u 10.

**Pull request merged**
